files:
  - source: /Source/Localization/en.lproj/Generated.strings
    translation: /Source/Localization/%osx_code%/%original_file_name%
pull_request_labels:
  - Skip-Changelog
commit_message: add new translations in %original_file_name% [ci skip]
append_commit_message: No
export_languages:
  - ca
  - de
  - pl
  - es
  - es-UY
