pull_request_labels:
  - Skip-Changelog
files:
  - source: /Source/Localization/en.lproj/Generated.strings
    translation: /Source/Localization/%osx_code%/%original_file_name%
    languages_mapping:
      osx_code:
        ca: ca.lproj
        ca-ES: ca.lproj
