# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    xcodes # ensure correct version of xcode is installed and selected
    api_key = app_store_connect_api_key(
      key_id: "4L8Z9W89TJ",
      issuer_id: "8985ca52-aba6-4f7a-91bb-d052a5b030fa",
      key_filepath: "~/.fastlane/AuthKey_4L8Z9W89TJ.p8"
    )
    increment_build_number(xcodeproj: "Planetary.xcodeproj")
    version_number = get_version_number(xcodeproj: "Planetary.xcodeproj", target: "Planetary")
    build_number = get_build_number
    gym(workspace: "Planetary.xcworkspace", scheme: "Planetary", clean: true, xcargs: "-allowProvisioningUpdates")
    changelog = read_changelog
    upload_to_testflight(changelog: changelog)
    stamp_changelog(section_identifier: "#{version_number} (#{build_number})")
    git_commit(message: "TestFlight deployment", path: "*")
    add_git_tag(tag: "v#{version_number}-#{build_number}")
    push_to_git_remote
    notification(
      subtitle: "Build uploaded", 
      message: "tap to open App Store Connect", 
      sound: "Pebble", 
      open: "https://appstoreconnect.apple.com/apps/1481617318/testflight/ios"
    )
  end
end

# Dynamically define 3 lanes:
# bump_major
# bump_minor
# bump_patch
# from: https://benscheirman.com/2020/10/managing-version-numbers-with-fastlane/
%w{major minor patch}.each do |part|
  lane "bump_#{part}".to_sym do
    increment_version_number_in_xcodeproj(bump_type: part, target: "Planetary")
  end
end
