# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Planetary.xcodeproj")
    build_app(workspace: "Planetary.xcworkspace", scheme: "Planetary")
    upload_to_testflight
  end
end

# Dynamically define 3 lanes:
# bump_major
# bump_minor
# bump_patch
# from: https://benscheirman.com/2020/10/managing-version-numbers-with-fastlane/
%w{major minor patch}.each do |part|
  lane "bump_#{part}".to_sym do
    increment_version_number_in_xcodeproj(bump_type: part, target: "Planetary")
  end
end
