name: Secrets
on:
  pull_request:
    paths:
      - 'Secrets/**'
jobs:
  unit_test:
    name: Unit Tests
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -workspace Planetary.xcworkspace -scheme Secrets -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -workspace Planetary.xcworkspace -scheme Secrets -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" | xcpretty
